//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentItem
    {
        public int vouchernumber { get; set; }
        public string itemcode { get; set; }
        public int quantity { get; set; }
        public string reason { get; set; }
    
        public virtual AdjustmentVoucher AdjustmentVoucher { get; set; }
        public virtual Item Item { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdjustmentVoucher()
        {
            this.AdjustmentItems = new HashSet<AdjustmentItem>();
        }
    
        public int vouchernumber { get; set; }
        public System.DateTime issuedate { get; set; }
        public double cost { get; set; }
        public int clerkcode { get; set; }
        public Nullable<int> approvercode { get; set; }
        public Nullable<System.DateTime> approvaldate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentItem> AdjustmentItems { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Disbursements = new HashSet<Disbursement>();
            this.Employees = new HashSet<Employee>();
            this.Requisitions = new HashSet<Requisition>();
        }
    
        public string deptcode { get; set; }
        public string deptname { get; set; }
        public string contactname { get; set; }
        public string phoneno { get; set; }
        public string faxno { get; set; }
        public string collectionpoint { get; set; }
        public Nullable<int> delegatecode { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public int del { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disbursement> Disbursements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisitions { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disbursement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disbursement()
        {
            this.DisbursementItems = new HashSet<DisbursementItem>();
        }
    
        public int disbursementid { get; set; }
        public string deptcode { get; set; }
        public int representativecode { get; set; }
        public Nullable<System.DateTime> collectiondate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementItem> DisbursementItems { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementItem
    {
        public int disbursementid { get; set; }
        public string itemcode { get; set; }
        public int allocatedquantity { get; set; }
        public Nullable<int> actualquantity { get; set; }
    
        public virtual Disbursement Disbursement { get; set; }
        public virtual Item Item { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AdjustmentVouchers = new HashSet<AdjustmentVoucher>();
            this.AdjustmentVouchers1 = new HashSet<AdjustmentVoucher>();
            this.Departments = new HashSet<Department>();
            this.Disbursements = new HashSet<Disbursement>();
            this.SOrders = new HashSet<SOrder>();
            this.SOrders1 = new HashSet<SOrder>();
            this.SOrders2 = new HashSet<SOrder>();
            this.Requisitions = new HashSet<Requisition>();
            this.Requisitions1 = new HashSet<Requisition>();
        }
    
        public int employeecode { get; set; }
        public string employeename { get; set; }
        public string employeeemail { get; set; }
        public string deptcode { get; set; }
        public string role { get; set; }
        public int del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentVoucher> AdjustmentVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentVoucher> AdjustmentVouchers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disbursement> Disbursements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrder> SOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrder> SOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrder> SOrders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisitions1 { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.AdjustmentItems = new HashSet<AdjustmentItem>();
            this.DisbursementItems = new HashSet<DisbursementItem>();
            this.OrderItems = new HashSet<OrderItem>();
            this.RequisitionItems = new HashSet<RequisitionItem>();
            this.TenderQuotations = new HashSet<TenderQuotation>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string itemcode { get; set; }
        public string category { get; set; }
        public string itemdescription { get; set; }
        public string bin { get; set; }
        public int quantityonhand { get; set; }
        public int reorderlevel { get; set; }
        public int reorderquantity { get; set; }
        public string unitofmeasure { get; set; }
        public string supplier1 { get; set; }
        public string supplier2 { get; set; }
        public string supplier3 { get; set; }
        public int del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentItem> AdjustmentItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementItem> DisbursementItems { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier4 { get; set; }
        public virtual Supplier Supplier5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenderQuotation> TenderQuotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int purchaseordernumber { get; set; }
        public string itemcode { get; set; }
        public int orderquantity { get; set; }
        public double cost { get; set; }
        public string remarks { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SOrder SOrder { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.RequisitionItems = new HashSet<RequisitionItem>();
        }
    
        public int requisitionid { get; set; }
        public string deptcode { get; set; }
        public int employeecode { get; set; }
        public Nullable<int> approvercode { get; set; }
        public Nullable<System.DateTime> approvaldate { get; set; }
        public int status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionItem
    {
        public int requisitionid { get; set; }
        public string itemcode { get; set; }
        public int quantity { get; set; }
        public int status { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOrder()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int purchaseordernumber { get; set; }
        public string suppliercode { get; set; }
        public int storeclerkcode { get; set; }
        public System.DateTime orderdate { get; set; }
        public Nullable<double> totalcost { get; set; }
        public Nullable<int> approvercode { get; set; }
        public Nullable<System.DateTime> approvaldate { get; set; }
        public Nullable<System.DateTime> expecteddeliverydate { get; set; }
        public string deliveryordernumber { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<int> receivercode { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Items = new HashSet<Item>();
            this.Items1 = new HashSet<Item>();
            this.Items2 = new HashSet<Item>();
            this.SOrders = new HashSet<SOrder>();
            this.TenderQuotations = new HashSet<TenderQuotation>();
        }
    
        public string suppliercode { get; set; }
        public string suppliername { get; set; }
        public string contactname { get; set; }
        public string phonenumber { get; set; }
        public string faxnumber { get; set; }
        public string address { get; set; }
        public string gstregistrationno { get; set; }
        public int del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrder> SOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenderQuotation> TenderQuotations { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderQuotation
    {
        public string suppliercode { get; set; }
        public string itemcode { get; set; }
        public double price { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionid { get; set; }
        public string itemcode { get; set; }
        public System.DateTime date { get; set; }
        public string deptsupplier { get; set; }
        public int quantitychange { get; set; }
        public int balance { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
